language: ruby
services:
  postgresql: "9.4"
rvm:
  - "2.4.1"
gemfile: Gemfile
env:
  - DB=postgresql
before_script:
  - psql -c 'create database serg_test;' -U postgres
  - cp config/database.yml.travis  config/database.yml
script:
  - bundle exec rails db:setup
  - bundle exec rails db:test:prepare
  - bundle exec rspec spec